name: contrack-docs
channels:
  - conda-forge
dependencies:
  - python=3.8.5
  - cartopy=0.18.0
  - xarray=0.16.1
  - numpy=1.19.2
  - scipy=1.5.2
  - pandas=1.1.3
  - matplotlib=3.3.2
  - pip=20.2.4
  - netcdf4=1.5.4

